version: '3'

services:
    bcb:
        image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
        ports: 
            - 8082:8082

    erp-itau:
        image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
        ports: 
            - 9091:9091

    mysql_key_manager:
        image: mysql:latest
        container_name: mysql_key_manager
        environment:
            - MYSQL_DATABASE=key_manager_grpc
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - mysql-volume:/var/lib/mysql
        ports:
            - 3306:3306

volumes:
    mysql-volume: