version: '3'

services:
    bcb:
        image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
        ports: 
            - 8082:8082

    erp-itau:
        image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
        ports: 
            - 9091:9091

    key_manager_grpc:
        build:
            dockerfile: ./Dockerfile
            context: .
        image: fmchagas/key-manager-grpc
        container_name: key-manager-grpc
        restart: on-failure
        ports:
            - 50051:50051
        environment:
            - DB_URL=jdbc:postgresql://postgres/key_manager_grpc
            - BD_USER=root
            - BD_PWD=root
            - ERP_ITAU_CONTAS_URL=http://erp-itau:9091/api/v1/clientes
            - BCB_URL=http://bcb:8082
            - DB_DIALECT=POSTGRES
            #- SERVER_PORT=5052
        depends_on:
            - postgres

    postgres:
        image: postgres:13.3-alpine
        container_name: db-km-grpc-container
        environment:
            - POSTGRES_DB=key_manager_grpc
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - TZ=GMT
        volumes:
            - postgres-volume-key-manager-grpc:/var/lib/postgresql/data
        ports:
            - 5432:5432

    pg_admin:
        image: dpage/pgadmin4:latest
        container_name: pg_admin
        environment:
            - PGADMIN_DEFAULT_EMAIL=user@domain.com
            - PGADMIN_DEFAULT_PASSWORD=SuperSecret
        ports:
            - 80:80
        depends_on:
            - postgres

volumes:
    postgres-volume-key-manager-grpc: