version: '3'

services:
    bcb:
        image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
        ports: 
            - 8082:8082

    erp-itau:
        image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
        ports: 
            - 9091:9091

    mysql_key_manager:
        image: mysql:latest
        container_name: mysql_key_manager
        environment:
            - MYSQL_DATABASE=key_manager_grpc
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - mysql-volume:/var/lib/mysql
        ports:
            - 3306:3306

    key_manager_grpc:
        build:
            dockerfile: ./Dockerfile
            context: .
        image: fmchagas/key-manager-grpc
        container_name: key_manager_grpc
        restart: on-failure
        ports:
            - 50051:50051
        environment:
            - DB_URL=jdbc:mysql://mysql_key_manager/key_manager_grpc
            - BD_USER=root
            - BD_PWD=root
            - ERP_ITAU_CONTAS_URL=http://erp-itau:9091/api/v1/clientes
            - BCB_URL=http://bcb:8082
            #- SERVER_PORT=5052
        depends_on:
            - mysql_key_manager

volumes:
    mysql-volume: