datasources:
  default:
    url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

jpa.default.properties.hibernate.hbm2ddl.auto: create
jpa.default.properties.hibernate.show_sql: false
#jpa.default.properties.hibernate.format_sql: true

# gRPC Server
grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 15m
    max-inbound-message-size: 1024