micronaut:
  application:
    name: orangeTalents04TemplatePixKeymanagerGrpc

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/key_manager_grpc`}
#    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PWD:postgres}
    schema-generate: CREATE_DROP
    dialect: ${DB_DIALECT:POSTGRES}

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: false

jpa:
  default:
    entity-scan:
      packages:
        - 'br.com.fmchagas.key_manager_grpc'

# URL clientes
erp:
  itau:
    contas:
      url: ${ERP_ITAU_CONTAS_URL:`http://localhost:9091/api/v1/clientes`}

# URL client BCB
bcb:
  url: ${BCB_URL:`http://localhost:8082`}

# gRPC Server
grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 15m
    max-inbound-message-size: 1024