apiVersion: v1
kind: Service
metadata:
  name: keymanager-grpc-svc-clusterip
spec:
  type: ClusterIP
  ports:
    - port: 50051
      #targetPort: 50051
  selector:
    app: key-manager-grpc #link key-manager-grpc-deployment