apiVersion: v1
kind: ConfigMap
metadata:
  name: keymanager-grpc-configmap
data:
  DB_URL: "jdbc:mysql://db-svc-keymanager-grpc/key_manager_grpc"
  BD_USER: "root"
  BD_PWD: "root"
  ERP_ITAU_CONTAS_URL: "http://ct-svc-erp-clusterip:9091/api/v1/clientes"
  BCB_URL: "http://ct-svc-pix-clusterip:8082"
  SERVER_PORT: "50051"