apiVersion: v1
kind: Service
metadata:
  name: app-keymanager-grpc-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      #targetPort: 50051
      nodePort: 30007
  selector:
    app: key-manager-grpc