apiVersion: v1
kind: Service
metadata:
  name: db-svc-keymanager-grpc
spec:
  type: ClusterIP
  ports:
    - port: 5432
      #targetPort: 5432
  selector:
    app: db-key-manager #Link Labels do db-deployment