apiVersion: v1
kind: Service
metadata:
  name: db-svc-node-port
spec:
  type: NodePort
  ports:
    - port: 3306
      #targetPort: 3306
      nodePort: 30002
  selector:
    app: db-mysql-key-manager